### ISSUE TITLE
Resuming graph activity after it was destroyed crashes the app

### ISSUE THREAD

**Issue by daniele-athome** [artnc/chronofile#9]
I'm assuming it happens because the activity is destroyed by the system due to memory pressure. Anyway here is the log:

```
01-15 09:43:44.134 E/arun.chronofil(3242): Not starting debugger since process cannot load the jdwp agent.
01-15 09:43:44.302 W/arun.chronofil(3242): Accessing hidden method Landroid/content/res/Resources$Theme;->rebase()V (dark greylist, linking)
01-15 09:43:44.327 I/Chronofile(3242): GraphActivity onCreate
01-15 09:43:44.338 E/MPChartLib-Utils(3242): Utils NOT INITIALIZED. You need to call Utils.init(...) at least once before calling Utils.convertDpToPixel(...). Otherwise conversion does not take place.
01-15 09:43:44.338 E/MPChartLib-Utils(3242): Utils NOT INITIALIZED. You need to call Utils.init(...) at least once before calling Utils.convertDpToPixel(...). Otherwise conversion does not take place.
01-15 09:43:44.344 I/Chronofile(3242): h0 onAttach
01-15 09:43:44.344 I/Chronofile(3242): h0 onCreate
01-15 09:43:44.344 I/Chronofile(3242): j0 onAttach
01-15 09:43:44.344 I/Chronofile(3242): j0 onCreate
01-15 09:43:44.345 I/Chronofile(3242): f onAttach
01-15 09:43:44.345 I/Chronofile(3242): f onCreate
01-15 09:43:44.441 D/AndroidRuntime(3242): Shutting down VM
01-15 09:43:44.444 E/AndroidRuntime(3242): FATAL EXCEPTION: main
01-15 09:43:44.444 E/AndroidRuntime(3242): Process: com.chaidarun.chronofile, PID: 3242
01-15 09:43:44.444 E/AndroidRuntime(3242): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chaidarun.chronofile/com.chaidarun.chronofile.GraphActivity}: java.lang.NullPointerException
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1976)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at android.os.Looper.loop(Looper.java:193)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at android.app.ActivityThread.main(ActivityThread.java:6912)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at java.lang.reflect.Method.invoke(Native Method)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
01-15 09:43:44.444 E/AndroidRuntime(3242): Caused by: java.lang.NullPointerException
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at com.chaidarun.chronofile.GraphActivity.onCreate(:8)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at android.app.Activity.performCreate(Activity.java:7148)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at android.app.Activity.performCreate(Activity.java:7139)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1293)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
01-15 09:43:44.444 E/AndroidRuntime(3242): 	... 11 more
```

**Comment by tom11298** [comment]
Hello, 

I ran into the same issue twice now, collapsing the data for the last week and second time around collapsing the past four days.
What I figured was that the TSV file was last updated when I had last turned off/restart my cell. If you restart the cell you are using it should update the TSV file and back up your data.
I am a mechanical engineering and my coding background is limited. hopefully this helps you.
